# Question 1: Pearson correlation coefficient is a measure of the linear relationship between two variables. Suppose you have collected data on the amount of time students spend studying for an exam and their final exam scores. Calculate the Pearson correlation coefficient between these two variables and interpret the result.

In [28]:
import numpy as np
import pandas as pd

np.random.seed(654)
n=1000
#time_studied = np.random.normal(8,12,size=n)
#exam_score = (time_studied**2)-3*time_studied + 2 +np.random.normal(0,5,size=n)

time_studied = np.array([10, 8, 9, 7, 6, 10, 5, 7, 8, 6])
exam_score = np.array([90, 85, 89, 80, 78, 93, 70, 82, 87, 75])


# Create dataframe
df = pd.DataFrame({'time_studied':time_studied,
                   'exam_score':exam_score})

df.head(10)

time_studied  exam_score
0            10          90
1             8          85
2             9          89
3             7          80
4             6          78
5            10          93
6             5          70
7             7          82
8             8          87
9             6          75

In [29]:
cor = df.corr(method='pearson')

In [30]:
cor

time_studied  exam_score
time_studied      1.000000    0.971948
exam_score        0.971948    1.000000

# Q2. Spearman's rank correlation is a measure of the monotonic relationship between two variables. Suppose you have collected data on the amount of sleep individuals get each night and their overall job satisfaction level on a scale of 1 to 10. Calculate the Spearman's rank correlation between these two variables and interpret the result.

In [32]:
import pandas as pd
dct = {
    'sleep': [8,7,6,5,8,7,6,5,4,7],
    'Job Satisfaction' : [9,6,4,7,8,5,3,6,2,7]
}
df = pd.DataFrame(dct)
df


sleep  Job Satisfaction
0      8                 9
1      7                 6
2      6                 4
3      5                 7
4      8                 8
5      7                 5
6      6                 3
7      5                 6
8      4                 2
9      7                 7

In [37]:
df.corr()

sleep  Job Satisfaction
sleep             1.00000           0.67177
Job Satisfaction  0.67177           1.00000

In [38]:
df.rank()

sleep  Job Satisfaction
0    9.5              10.0
1    7.0               5.5
2    4.5               3.0
3    2.5               7.5
4    9.5               9.0
5    7.0               4.0
6    4.5               2.0
7    2.5               5.5
8    1.0               1.0
9    7.0               7.5

In [39]:
df.rank().corr()

sleep  Job Satisfaction
sleep             1.000000          0.660516
Job Satisfaction  0.660516          1.000000

# Q3. Suppose you are conducting a study to examine the relationship between the number of hours of exercise per week and body mass index (BMI) in a sample of adults. You collected data on both variables for 50 participants. Calculate the Pearson correlation coefficient and the Spearman's rank correlation between these two variables and compare the results.

In [60]:
import pandas as pd
import numpy as np

# Set Random seed
np.random.seed(987)

# Generate Sample Data
n = 50
exercise_hours = np.random.normal(loc=5 , scale=1.5, size=n)
BMI =  10 +np.random.normal(loc=0, scale=5, size=n)
df = pd.DataFrame({'exercise_hours':exercise_hours,
                  'BMI':BMI})

#df[['exercise_hours']].std , df[['exercise_hours']].mean

df.head()

exercise_hours        BMI
0        2.471109  14.673901
1        2.793320   5.133346
2        4.832300  16.984414
3        6.554555   2.039814
4        5.991560   9.487029

In [61]:
df_corr = df.corr(method='pearson')

In [62]:
df_corr

exercise_hours       BMI
exercise_hours        1.000000 -0.234755
BMI                  -0.234755  1.000000

In [63]:
df_corr_spr=df.corr(method='spearman')

In [64]:
df_corr_spr

exercise_hours       BMI
exercise_hours        1.000000 -0.189916
BMI                  -0.189916  1.000000

### Both Spearman's Correlation and Pearson's Correlation show's strong negative Correlation between BMI and exercise time


# Question 4 : A researcher is interested in examining the relationship between the number of hours individuals spend watching television per day and their level of physical activity. The researcher collected data on both variables from a sample of 50 participants. Calculate the Pearson correlation coefficient between these two variables.

In [71]:
import numpy as np
import pandas as pd
from scipy.stats import pearsonr

# Set the random seed for reproducibility
np.random.seed(12)

# Generate synthetic data for hours of TV watching and physical activity
tv_hours = np.random.normal(3, 1, 50)
physical_activity =  5+np.random.normal(0,1,50)

# Showing Dataframe
df = pd.DataFrame({'tv_hours':tv_hours,'physical_activity':physical_activity})
print(df.head())

   tv_hours  physical_activity
0  3.472986           5.232490
1  2.318574           5.867612
2  3.242439           3.851787
3  1.299264           7.114344
4  3.753143           6.000943


In [74]:
pearson_corr, pval = pearsonr(df['tv_hours'],df['physical_activity'])

print('Pearson Correlation Coefficient', pearson_corr)

print('P value', pval)

Pearson Correlation Coefficient -0.18196898026727176
P value 0.2059571013990125


In [73]:
df.corr(method='pearson')

tv_hours  physical_activity
tv_hours           1.000000          -0.181969
physical_activity -0.181969           1.000000

#### Low Negative Correlation found between tv_hours and phyiscal_activity

# Question 5 : A survey was conducted to examine the relationship between age and preference for a particular brand of soft drink. The survey results are shown below:


In [76]:
import pandas as pd

data = {'age': [25,42,37,19,31,28],
        'soft drink preference': ['Coke', 'Pepsi', 'Mountain Dew', 'Coke','Pepsi','Coke']}

In [77]:
df = pd.DataFrame(data)
df

age soft drink preference
0   25                  Coke
1   42                 Pepsi
2   37          Mountain Dew
3   19                  Coke
4   31                 Pepsi
5   28                  Coke

In [80]:
from scipy.stats import chi2_contingency
# Create a contingency table
contingency_table = pd.crosstab(df['age'], df['soft drink preference'])

# Print the contingency table
print(contingency_table)

soft drink preference  Coke  Mountain Dew  Pepsi
age                                             
19                        1             0      0
25                        1             0      0
28                        1             0      0
31                        0             0      1
37                        0             1      0
42                        0             0      1


In [81]:
# Perform the chi-square test of independence
chi2_stat, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-square test statistic:", chi2_stat)
print("p-value:", pval)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

Chi-square test statistic: 12.000000000000002
p-value: 0.28505650031663116
Degrees of freedom: 10
Expected frequencies:
 [[0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]]


# Q6. A company is interested in examining the relationship between the number of sales calls made per day and the number of sales made per week. The company collected data on both variables from a sample of 30 sales representatives. Calculate the Pearson correlation coefficient between these two variables.

In [83]:
import numpy as np
import pandas as pd
from scipy.stats import pearsonr

# Generate synthetic data
np.random.seed(1234)  # for reproducibility
sales_calls = np.random.randint(50, 100, size=30)
sales_per_week = np.round(sales_calls * np.random.uniform(500, 200, size=30), decimals=0)

# Create dataframe for printing
df = pd.DataFrame({'sales_calls':sales_calls,'sales_per_week':sales_per_week})
print(df.head())

   sales_calls  sales_per_week
0           97         22624.0
1           69         14066.0
2           88         40899.0
3           62         23676.0
4           74         26949.0


In [87]:
# Calculate the Pearson correlation coefficient
pearson_corr, pval = pearsonr(df['sales_calls'], df['sales_per_week'])

# Print the results
print("Pearson correlation coefficient:", pearson_corr)

Pearson correlation coefficient: 0.5445192570910078


### A positive Pearson correlation coefficient indicate a positive correlation between the number of sales calls made per day and the number of sales made per week