In [1]:
import numpy as np

In [3]:
list_ = ['1', '2','3','4','5']

In [4]:
array_list = np.array(object=list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [15]:
type(list_)

list

In [16]:
type(array_list)

numpy.ndarray

# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [32]:
for x in range(len(list_)):
    print(f" {type(list_[x])}")

 <class 'str'>
 <class 'str'>
 <class 'str'>
 <class 'str'>
 <class 'str'>


In [30]:
for x in array_list:
    print(type(x))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
array_list? If so then print the data types of each and every element present in both the variables, list_
and array_list.

In [35]:
list_ = ['1', '2','3','4','5']

In [36]:
for x in range(len(list_)):
    print(f" {type(list_[x])}")

 <class 'str'>
 <class 'str'>
 <class 'str'>
 <class 'str'>
 <class 'str'>


In [33]:
array_list = np.array(object = list_, dtype = int)


In [34]:
for x in array_list:
    print(type(x))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Yes, there will be difference in the data type for both list and numpy array because we change the data type of array_list from string to integer. That is why array_list type showing numpy.int32

In [37]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [38]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [41]:
num_array.shape

(2, 3)

In [42]:
num_array.size

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [43]:
import numpy.matlib as nm

In [45]:
# Creating matrix using matrix library
nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [47]:
# creating matrix using numpy
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [49]:
# creating identity matrix using numpy
np_identity=np.eye(5,5)
np_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
# creating identity matrix using matlib
nm_identity= nm.eye(5,5)
nm_identity

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])